alert("OHAYOUU! SHANE HAHAHAHAHAH")
alert("MAY NEXT SAKA PREVIOUS BUTTON KADA PAGE PINDUTIN MO NA LANG")
alert("HULAAN MO UNG KANTA NA NAKALAGAY SA BAWAT PIC AH HASHSHA")
alert("SANA MAGUSTUHAN MO UWU HAHAHAHHAAH")